#!/usr/bin/env Rscript

# Generate a complete, text-only compatibility fixture from R itself.
# Usage: Rscript --vanilla tools/generate-fixture.R 4.5.0

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1L) {
    stop("usage: generate-fixture.R <R-version>")
}

target_version <- args[[1L]]
suppressWarnings(RNGversion(target_version))
set.seed(42)

hex_bits <- function(values) {
    vapply(
        values,
        function(value) {
            bytes <- writeBin(value, raw(), size = 8L, endian = "big")
            paste(sprintf("%02x", as.integer(bytes)), collapse = "")
        },
        character(1L)
    )
}

emit <- function(name, values) {
    cat(name, "=", paste(values, collapse = ","), "\n", sep = "")
}

cat("# Generated by tools/generate-fixture.R; do not hand-edit.\n")
cat("target_version=", target_version, "\n", sep = "")
cat("generator_runtime=", R.version.string, "\n", sep = "")

uniforms <- runif(100)
emit("runif_bits", hex_bits(uniforms))
emit("state_after_runif", .Random.seed)

normals <- rnorm(100)
emit("rnorm_bits", hex_bits(normals))
emit("state_after_rnorm", .Random.seed)

permutation <- sample(1:20)
emit("permutation", permutation)
emit("state_after_permutation", .Random.seed)
