#!/usr/bin/env Rscript

# Generate the R 4.6 L'Ecuyer-CMRG fixture, including stream jumps.

suppressWarnings(RNGversion("4.6.0"))
RNGkind("L'Ecuyer-CMRG")
set.seed(42)

hex_bits <- function(values) {
    vapply(
        values,
        function(value) {
            bytes <- writeBin(value, raw(), size = 8L, endian = "big")
            paste(sprintf("%02x", as.integer(bytes)), collapse = "")
        },
        character(1L)
    )
}

emit <- function(name, values) {
    cat(name, "=", paste(values, collapse = ","), "\n", sep = "")
}

cat("# Generated by tools/generate-lecuyer-fixture.R; do not hand-edit.\n")
cat("target_version=4.6.0\n")
cat("generator_runtime=", R.version.string, "\n", sep = "")

initial_state <- .Random.seed
emit("initial_state", initial_state)
emit("next_stream", parallel::nextRNGStream(initial_state))
emit("next_substream", parallel::nextRNGSubStream(initial_state))

uniforms <- runif(100)
emit("runif_bits", hex_bits(uniforms))
emit("state_after_runif", .Random.seed)

normals <- rnorm(100)
emit("rnorm_bits", hex_bits(normals))
emit("state_after_rnorm", .Random.seed)

permutation <- sample.int(20L)
emit("permutation", permutation)
emit("state_after_permutation", .Random.seed)
