#!/usr/bin/env Rscript

# Generate R 4.6 pnorm5 values across central, intermediate, and far tails.

hex_bits <- function(values) {
    vapply(
        values,
        function(value) {
            bytes <- writeBin(value, raw(), size = 8L, endian = "big")
            paste(sprintf("%02x", as.integer(bytes)), collapse = "")
        },
        character(1L)
    )
}

emit <- function(name, values) {
    cat(name, "=", paste(values, collapse = ","), "\n", sep = "")
}

cat("# Generated by tools/generate-pnorm-fixture.R; do not hand-edit.\n")
cat("target_version=4.6.0\n")
cat("generator_runtime=", R.version.string, "\n", sep = "")

standard <- c(
    -1e100, -50, -40, -38.5, -38.4674, -38, -10, -8.2924, -8,
    -sqrt(32), -1, -0.67448975, -0.1, 0, 0.1, 0.67448975, 1,
    sqrt(32), 8, 8.2924, 10, 38, 38.4674, 38.5, 40, 50, 1e100
)
emit("standard_lower_plain_bits", hex_bits(pnorm(standard, lower.tail = TRUE)))
emit("standard_upper_plain_bits", hex_bits(pnorm(standard, lower.tail = FALSE)))
emit("standard_lower_log_bits", hex_bits(pnorm(standard, lower.tail = TRUE, log.p = TRUE)))
emit("standard_upper_log_bits", hex_bits(pnorm(standard, lower.tail = FALSE, log.p = TRUE)))

shifted <- c(-100, -7.25, -1, 2.5, 6, 9.75, 100)
emit("shifted_lower_plain_bits", hex_bits(pnorm(shifted, 2.5, 3.25, TRUE, FALSE)))
emit("shifted_upper_plain_bits", hex_bits(pnorm(shifted, 2.5, 3.25, FALSE, FALSE)))
emit("shifted_lower_log_bits", hex_bits(pnorm(shifted, 2.5, 3.25, TRUE, TRUE)))
emit("shifted_upper_log_bits", hex_bits(pnorm(shifted, 2.5, 3.25, FALSE, TRUE)))
