#!/usr/bin/env Rscript

# Reproduce the RNG-consuming portion of rye.optimize's inner loop at
# carbocation/rye commit 2541fe03a163da92ce9279d87bf75a089b5ebf60.

suppressWarnings(RNGversion("4.6.0"))
set.seed(42)

hex_bits <- function(values) {
    vapply(
        values,
        function(value) {
            bytes <- writeBin(value, raw(), size = 8L, endian = "big")
            paste(sprintf("%02x", as.integer(bytes)), collapse = "")
        },
        character(1L)
    )
}

iterations <- 50L
alpha_indices <- integer(iterations)
alpha_normals <- numeric(iterations)
weight_indices <- integer(iterations)
weight_normals <- numeric(iterations)
acceptance_uniforms <- numeric(iterations)

for (iteration in seq(iterations)) {
    alpha_indices[[iteration]] <- sample.int(7L, 1L)
    alpha_normals[[iteration]] <- rnorm(n = 1L)
    weight_indices[[iteration]] <- sample.int(11L, 1L)
    weight_normals[[iteration]] <- rnorm(n = 1L)

    # pnorm() occurs here in Rye but does not consume RNG state.
    acceptance_uniforms[[iteration]] <- runif(n = 1L, min = 0, max = 1)
}

emit <- function(name, values) {
    cat(name, "=", paste(values, collapse = ","), "\n", sep = "")
}

cat("# Generated by tools/generate-rye-fixture.R; do not hand-edit.\n")
cat("source_commit=2541fe03a163da92ce9279d87bf75a089b5ebf60\n")
cat("generator_runtime=", R.version.string, "\n", sep = "")
emit("alpha_indices", alpha_indices)
emit("alpha_normal_bits", hex_bits(alpha_normals))
emit("weight_indices", weight_indices)
emit("weight_normal_bits", hex_bits(weight_normals))
emit("acceptance_uniform_bits", hex_bits(acceptance_uniforms))
emit("final_state", .Random.seed)
